name: Build App Image

on:
  workflow_dispatch:  # manual trigger

permissions:  # ðŸ‘ˆ required for OIDC delegation
  id-token: write
  contents: read

jobs:
  build:
    uses: Ajithkumar8006/build-and-publish-docker-image/.github/workflows/build-and-push.yml@main
    with:
      image_name: ubuntu-app
      tag: v1.0.0
      region: us-central1
      project_id: apigee-12092025
      workload_identity_provider: projects/352535210260/locations/global/workloadIdentityPools/github-pool/providers/github-provider
      service_account: github-actions@apigee-12092025.iam.gserviceaccount.com
      context: ./ubuntu
      dockerfile: ./ubuntu/Dockerfile
